# Changelog

All notable changes to this project will be documented in this file.

## [0.1.5] - 2024-07-19

### 🚀 Features

- Use deterministic command execution
- Preserve EntityIds when deserializing a World
- Allow users to replace the job_system of a World
- Add vacuum method to the database
- Add IntoOnceSystem
- Query::subset
- Add Has<T> queries
- Query an entity's EntityTable
- Remove empty archetypes from the public interface
- Support running futures on the JobSystem

### 🐛 Bug Fixes

- Fix stage execution when feature: parallel is disabled
- Fix a bug where new archetypes would invalidate exiting ids
- Fix archetypes of bundles where the entity already has some of the bundle components

### 🚜 Refactor

- Return commands result in run_system
- [**breaking**] Remove system pipes
- [**breaking**] Remove component setters from the public interface

### Misc

- Panic on incorrect Command use

<!-- generated by git-cliff -->
